from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 869)
        font = QtGui.QFont()
        font.setPointSize(20)
        Form.setFont(font)
        self.labelproductsunusable = QtWidgets.QLabel(parent=Form)
        self.labelproductsunusable.setGeometry(QtCore.QRect(110, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelproductsunusable.setFont(font)
        self.labelproductsunusable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelproductsunusable.setObjectName("labelproductsunusable")
        self.categoryfilter = QtWidgets.QComboBox(parent=Form)
        self.categoryfilter.setGeometry(QtCore.QRect(20, 90, 301, 41))
        self.categoryfilter.setObjectName("categoryfilter")
        self.categoryfilter.addItem("")
        self.brandfilter = QtWidgets.QComboBox(parent=Form)
        self.brandfilter.setGeometry(QtCore.QRect(330, 90, 301, 41))
        self.brandfilter.setObjectName("brandfilter")
        self.brandfilter.addItem("")
        self.mainlistproducts = QtWidgets.QListWidget(parent=Form)
        self.mainlistproducts.setGeometry(QtCore.QRect(30, 150, 571, 501))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(14)
        self.mainlistproducts.setFont(font)
        self.mainlistproducts.setObjectName("mainlistproducts")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 670, 571, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.diabeticcheck = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(14)
        self.diabeticcheck.setFont(font)
        self.diabeticcheck.setObjectName("diabeticcheck")
        self.horizontalLayout.addWidget(self.diabeticcheck)
        self.kidscheck = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(14)
        self.kidscheck.setFont(font)
        self.kidscheck.setObjectName("kidscheck")
        self.horizontalLayout.addWidget(self.kidscheck)
        self.vegancheck = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(14)
        self.vegancheck.setFont(font)
        self.vegancheck.setObjectName("vegancheck")
        self.horizontalLayout.addWidget(self.vegancheck)
        self.addamountof = QtWidgets.QSpinBox(parent=Form)
        self.addamountof.setMinimum(1)
        self.addamountof.setGeometry(QtCore.QRect(170, 770, 161, 61))
        self.addamountof.setObjectName("addamountof")
        self.amountunusable = QtWidgets.QLabel(parent=Form)
        self.amountunusable.setGeometry(QtCore.QRect(40, 770, 111, 61))
        self.amountunusable.setObjectName("amountunusable")
        self.addProducts = QtWidgets.QPushButton(parent=Form)
        self.addProducts.setGeometry(QtCore.QRect(350, 770, 241, 61))
        self.addProducts.setObjectName("addProducts")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelproductsunusable.setText(_translate("Form", "Продукты"))
        self.categoryfilter.setItemText(0, _translate("Form", "По категориям"))
        self.brandfilter.setItemText(0, _translate("Form", "По брендам"))
        self.diabeticcheck.setText(_translate("Form", "Для диабетиков"))
        self.kidscheck.setText(_translate("Form", "Для малышей"))
        self.vegancheck.setText(_translate("Form", "Для веганов"))
        self.amountunusable.setText(_translate("Form", "Кол-во"))
        self.addProducts.setText(_translate("Form", "Добавить"))