from PyQt6 import QtCore, QtGui, QtWidgets
from testlayout2 import *

class Ui_FinalForm(object):
    def setupUi(self, FinalForm):
        FinalForm.setObjectName("FinalForm")
        FinalForm.resize(633, 866)
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(20)
        FinalForm.setFont(font)
        self.unusable = QtWidgets.QLabel(parent=FinalForm)
        self.unusable.setGeometry(QtCore.QRect(140, 0, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.unusable.setFont(font)
        self.unusable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.unusable.setObjectName("unusable")
        self.finalprice = QtWidgets.QLabel(parent=FinalForm)
        self.finalprice.setGeometry(QtCore.QRect(120, 70, 381, 81))
        self.finalprice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.finalprice.setObjectName("finalprice")
        self.pushButton = QtWidgets.QPushButton(parent=FinalForm)
        self.pushButton.setGeometry(QtCore.QRect(40, 620, 571, 71))
        self.pushButton.setObjectName("pushButton")
        self.puchaseditems = QtWidgets.QListWidget(parent=FinalForm)
        self.puchaseditems.setGeometry(QtCore.QRect(40, 170, 571, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setBold(True)
        font.setWeight(75)
        self.puchaseditems.setFont(font)
        self.puchaseditems.setObjectName("puchaseditems")
        self.pushButton_2 = QtWidgets.QPushButton(parent=FinalForm)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 780, 571, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=FinalForm)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 700, 571, 71))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(FinalForm)
        QtCore.QMetaObject.connectSlotsByName(FinalForm)

    def retranslateUi(self, FinalForm):
        _translate = QtCore.QCoreApplication.translate
        FinalForm.setWindowTitle(_translate("FinalForm", "Form"))
        self.unusable.setText(_translate("FinalForm", "Итоговая стоимость"))
        self.finalprice.setText(_translate("FinalForm", "0 рублей"))
        self.pushButton.setText(_translate("FinalForm", "Перейти к оплате"))
        self.pushButton_2.setText(_translate("FinalForm", "Назад"))
        self.pushButton_3.setText(_translate("FinalForm", "Перейти к оплате (без чека)"))
